--- # Application Preferences File - Brave
application:
      name         : brave
      path         : C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
load-delay: 2
local-dimensions:
      0:
            X-Origin          : 0
            Y-Origin          : 0
            Width             : 1277
            Height            : 800
      1:
            X-Origin          : 0
            Y-Origin          : 0
            Width             : 1277
            Height            : 800
      2:
            X-Origin          : 0
            Y-Origin          : 0
            Width             : 1277
            Height            : 800
      3:
            X-Origin          : 0
            Y-Origin          : 0
            Width             : 1277
            Height            : 800
remote-dimensions:
      0:
            X-Origin          : 1913
            Y-Origin          : 0
            Width             : 1277
            Height            : 800
      1:
            X-Origin          : 3190
            Y-Origin          : 0
            Width             : 1277
            Height            : 800
      2:
            X-Origin          : 1913
            Y-Origin          : 800
            Width             : 1277
            Height            : 800
      3:
            X-Origin          : 3190
            Y-Origin          : 800
            Width             : 1277
            Height            : 800
comments: >
      Local dimensions are set to produce a dashboard on the projector at home in 1080p 2x2 gridded.
      Remote dimensions are set to produce a dashboard on the Dell Ultrasharp at work in 2K 2x2 gridded.