--- # Application Preferences File - Obsidian
application:
      name         : Obsidian
      path         : C:\Users\leToads\AppData\Local\Obsidian\Obsidian.exe
load-delay: 2
local-dimensions:
      X-Origin     : 3413
      Y-Origin     : 0
      Width        : 853
      Height       : 1400
remote-dimensions:
      X-Origin     : 0
      Y-Origin     : 0
      Width        : 1920
      Height       : 1080
comments: >
  Any comments may be entered from this point onward.