--- # Application Preferences File - Spotify Premium
application:
      name         : Spotify
      path         : C:\Users\asfarr\AppData\Roaming\Spotify\Spotify.exe
load-delay: 4
local-dimensions:
      X-Origin     : 4260
      Y-Origin     : 0
      Width        : 865
      Height       : 1400
remote-dimensions:
      X-Origin     : 3520
      Y-Origin     : 0
      Width        : 960
      Height       : 1040
comments: >
  Any comments may be entered from this point onward.