--- # Application Preferences File - Obsidian
id: 00
load-delay: 8
application:
      name         : Obsidian
      path         : C:\Users\leToads\AppData\Local\Obsidian\Obsidian.exe
dimensions_local:
      X-Origin     : 3413
      Y-Origin     : 0
      Width        : 853
      Height       : 1400
comments: >
  Any comments may be entered from this point onward.